name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Clear pip cache and uninstall numpy and pandas
        run: |
          pip cache purge
          pip uninstall -y numpy pandas || true

      - name: Install Dependencies fresh (no cache)
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run Lint (basic check)
        run: |
          python -m py_compile app/*.py cli/*.py

      - name: Build Docker Image
        run: |
          docker build -t nextrole-test .

      - name: Set environment variable for CI
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Run CLI Matcher Test (skips GUI in CI)
        run: |
          python cli/match.py --jd data/job_descriptions/sample_jd.txt --resumes data/test_resumes
